
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed3;

	private global::Gtk.Entry entry5;

	private global::Gtk.Button button16;

	private global::Gtk.Button button17;

	private global::Gtk.Button button18;

	private global::Gtk.Button button19;

	private global::Gtk.Button button20;

	private global::Gtk.Button button21;

	private global::Gtk.Button button22;

	private global::Gtk.Button button23;

	private global::Gtk.Button button24;

	private global::Gtk.Button button25;

	private global::Gtk.Button button26;

	private global::Gtk.Button button27;

	private global::Gtk.Button button28;

	private global::Gtk.Button button29;

	private global::Gtk.Button button30;

	private global::Gtk.Button button31;

	private global::Gtk.Button button32;

	private global::Gtk.Button button33;

	private global::Gtk.Button button34;

	private global::Gtk.Button button35;

	private global::Gtk.Button button36;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 205;
		this.HeightRequest = 235;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calculator By Álvaro González");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 185;
		this.DefaultHeight = 210;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.WidthRequest = 205;
		this.fixed3.HeightRequest = 235;
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.WidthRequest = 195;
		this.entry5.HeightRequest = 25;
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.fixed3.Add(this.entry5);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry5]));
		w1.X = 5;
		w1.Y = 5;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button16 = new global::Gtk.Button();
		this.button16.WidthRequest = 35;
		this.button16.HeightRequest = 35;
		this.button16.CanFocus = true;
		this.button16.Name = "button16";
		this.button16.UseUnderline = true;
		this.button16.Label = global::Mono.Unix.Catalog.GetString("CE");
		this.fixed3.Add(this.button16);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button16]));
		w2.X = 5;
		w2.Y = 35;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button17 = new global::Gtk.Button();
		this.button17.WidthRequest = 35;
		this.button17.HeightRequest = 35;
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString("7");
		this.fixed3.Add(this.button17);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button17]));
		w3.X = 5;
		w3.Y = 75;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button18 = new global::Gtk.Button();
		this.button18.WidthRequest = 35;
		this.button18.HeightRequest = 35;
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = global::Mono.Unix.Catalog.GetString("4");
		this.fixed3.Add(this.button18);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button18]));
		w4.X = 5;
		w4.Y = 115;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button19 = new global::Gtk.Button();
		this.button19.WidthRequest = 35;
		this.button19.HeightRequest = 35;
		this.button19.CanFocus = true;
		this.button19.Name = "button19";
		this.button19.UseUnderline = true;
		this.button19.Label = global::Mono.Unix.Catalog.GetString("1");
		this.fixed3.Add(this.button19);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button19]));
		w5.X = 5;
		w5.Y = 155;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button20 = new global::Gtk.Button();
		this.button20.WidthRequest = 35;
		this.button20.HeightRequest = 35;
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString("BI");
		this.fixed3.Add(this.button20);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button20]));
		w6.X = 45;
		w6.Y = 35;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button21 = new global::Gtk.Button();
		this.button21.WidthRequest = 35;
		this.button21.HeightRequest = 35;
		this.button21.CanFocus = true;
		this.button21.Name = "button21";
		this.button21.UseUnderline = true;
		this.button21.Label = global::Mono.Unix.Catalog.GetString("HX");
		this.fixed3.Add(this.button21);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button21]));
		w7.X = 85;
		w7.Y = 35;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button22 = new global::Gtk.Button();
		this.button22.WidthRequest = 35;
		this.button22.HeightRequest = 35;
		this.button22.CanFocus = true;
		this.button22.Name = "button22";
		this.button22.UseUnderline = true;
		this.button22.Label = global::Mono.Unix.Catalog.GetString("(");
		this.fixed3.Add(this.button22);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button22]));
		w8.X = 125;
		w8.Y = 35;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button23 = new global::Gtk.Button();
		this.button23.WidthRequest = 35;
		this.button23.HeightRequest = 35;
		this.button23.CanFocus = true;
		this.button23.Name = "button23";
		this.button23.UseUnderline = true;
		this.button23.Label = global::Mono.Unix.Catalog.GetString(")");
		this.fixed3.Add(this.button23);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button23]));
		w9.X = 165;
		w9.Y = 35;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button24 = new global::Gtk.Button();
		this.button24.WidthRequest = 35;
		this.button24.HeightRequest = 35;
		this.button24.CanFocus = true;
		this.button24.Name = "button24";
		this.button24.UseUnderline = true;
		this.button24.Label = global::Mono.Unix.Catalog.GetString("8");
		this.fixed3.Add(this.button24);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button24]));
		w10.X = 45;
		w10.Y = 75;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button25 = new global::Gtk.Button();
		this.button25.WidthRequest = 35;
		this.button25.HeightRequest = 35;
		this.button25.CanFocus = true;
		this.button25.Name = "button25";
		this.button25.UseUnderline = true;
		this.button25.Label = global::Mono.Unix.Catalog.GetString("5");
		this.fixed3.Add(this.button25);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button25]));
		w11.X = 45;
		w11.Y = 115;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button26 = new global::Gtk.Button();
		this.button26.WidthRequest = 35;
		this.button26.HeightRequest = 35;
		this.button26.CanFocus = true;
		this.button26.Name = "button26";
		this.button26.UseUnderline = true;
		this.button26.Label = global::Mono.Unix.Catalog.GetString("2");
		this.fixed3.Add(this.button26);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button26]));
		w12.X = 45;
		w12.Y = 155;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button27 = new global::Gtk.Button();
		this.button27.WidthRequest = 35;
		this.button27.HeightRequest = 35;
		this.button27.CanFocus = true;
		this.button27.Name = "button27";
		this.button27.UseUnderline = true;
		this.button27.Label = global::Mono.Unix.Catalog.GetString("9");
		this.fixed3.Add(this.button27);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button27]));
		w13.X = 85;
		w13.Y = 75;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button28 = new global::Gtk.Button();
		this.button28.WidthRequest = 35;
		this.button28.HeightRequest = 35;
		this.button28.CanFocus = true;
		this.button28.Name = "button28";
		this.button28.UseUnderline = true;
		this.button28.Label = global::Mono.Unix.Catalog.GetString("6");
		this.fixed3.Add(this.button28);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button28]));
		w14.X = 85;
		w14.Y = 115;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button29 = new global::Gtk.Button();
		this.button29.WidthRequest = 35;
		this.button29.HeightRequest = 35;
		this.button29.CanFocus = true;
		this.button29.Name = "button29";
		this.button29.UseUnderline = true;
		this.button29.Label = global::Mono.Unix.Catalog.GetString("3");
		this.fixed3.Add(this.button29);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button29]));
		w15.X = 85;
		w15.Y = 155;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button30 = new global::Gtk.Button();
		this.button30.WidthRequest = 35;
		this.button30.HeightRequest = 35;
		this.button30.CanFocus = true;
		this.button30.Name = "button30";
		this.button30.UseUnderline = true;
		this.button30.Label = global::Mono.Unix.Catalog.GetString("*");
		this.fixed3.Add(this.button30);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button30]));
		w16.X = 125;
		w16.Y = 75;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button31 = new global::Gtk.Button();
		this.button31.WidthRequest = 35;
		this.button31.HeightRequest = 35;
		this.button31.CanFocus = true;
		this.button31.Name = "button31";
		this.button31.UseUnderline = true;
		this.button31.Label = global::Mono.Unix.Catalog.GetString("+");
		this.fixed3.Add(this.button31);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button31]));
		w17.X = 125;
		w17.Y = 115;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button32 = new global::Gtk.Button();
		this.button32.WidthRequest = 35;
		this.button32.HeightRequest = 35;
		this.button32.CanFocus = true;
		this.button32.Name = "button32";
		this.button32.UseUnderline = true;
		this.button32.Label = global::Mono.Unix.Catalog.GetString("=");
		this.fixed3.Add(this.button32);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button32]));
		w18.X = 125;
		w18.Y = 155;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button33 = new global::Gtk.Button();
		this.button33.WidthRequest = 35;
		this.button33.HeightRequest = 35;
		this.button33.CanFocus = true;
		this.button33.Name = "button33";
		this.button33.UseUnderline = true;
		this.button33.Label = global::Mono.Unix.Catalog.GetString("/");
		this.fixed3.Add(this.button33);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button33]));
		w19.X = 165;
		w19.Y = 75;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button34 = new global::Gtk.Button();
		this.button34.WidthRequest = 35;
		this.button34.HeightRequest = 35;
		this.button34.CanFocus = true;
		this.button34.Name = "button34";
		this.button34.UseUnderline = true;
		this.button34.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed3.Add(this.button34);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button34]));
		w20.X = 165;
		w20.Y = 115;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button35 = new global::Gtk.Button();
		this.button35.WidthRequest = 35;
		this.button35.HeightRequest = 35;
		this.button35.CanFocus = true;
		this.button35.Name = "button35";
		this.button35.UseUnderline = true;
		this.button35.Label = global::Mono.Unix.Catalog.GetString("ANS");
		this.fixed3.Add(this.button35);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button35]));
		w21.X = 165;
		w21.Y = 155;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button36 = new global::Gtk.Button();
		this.button36.WidthRequest = 35;
		this.button36.HeightRequest = 35;
		this.button36.CanFocus = true;
		this.button36.Name = "button36";
		this.button36.UseUnderline = true;
		this.button36.Label = global::Mono.Unix.Catalog.GetString("0");
		this.fixed3.Add(this.button36);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button36]));
		w22.X = 45;
		w22.Y = 195;
		this.Add(this.fixed3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button16.Clicked += new global::System.EventHandler(this.ButtonClick_ce);
		this.button17.Clicked += new global::System.EventHandler(this.ButtonClick_7);
		this.button18.Clicked += new global::System.EventHandler(this.ButtonClick_4);
		this.button19.Clicked += new global::System.EventHandler(this.ButtonClick_1);
		this.button20.Clicked += new global::System.EventHandler(this.ButtonClick_bi);
		this.button22.Clicked += new global::System.EventHandler(this.ButtonClick_leftp);
		this.button23.Clicked += new global::System.EventHandler(this.ButtonClick_rightp);
		this.button24.Clicked += new global::System.EventHandler(this.ButtonClick_8);
		this.button25.Clicked += new global::System.EventHandler(this.ButtonClick_5);
		this.button26.Clicked += new global::System.EventHandler(this.ButtonClick_2);
		this.button27.Clicked += new global::System.EventHandler(this.ButtonClick_9);
		this.button28.Clicked += new global::System.EventHandler(this.ButtonClick_6);
		this.button29.Clicked += new global::System.EventHandler(this.ButtonClick_3);
		this.button30.Clicked += new global::System.EventHandler(this.ButtonClick_mul);
		this.button31.Clicked += new global::System.EventHandler(this.ButtonClick_plu);
		this.button33.Clicked += new global::System.EventHandler(this.ButtonClick_div);
		this.button36.Clicked += new global::System.EventHandler(this.ButtonClick_0);
	}
}
